version: '3.8'
services:
  nextjs:
    container_name: nextjs
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production