version: '3.8'
services:
  nextjs-production:
    container_name: nextjs-production
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  nextjs-development:
    container_name: nextjs-development
    restart: always
    build:
      context: ./
      dockerfile: development.Dockerfile
      target: local
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development